name: Build and Deploy Docs

on:
  push:
    branches:
      - main # Or any other branch where you want to trigger the docs deployment

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use your project's node version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the docs using TypeDoc
      - name: Build docs
        run: npm run docs

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
